import { APIEndpoint, EndpointParameter } from './types'

export class APIExporter {
  // Export to OpenAPI 3.0 specification
  exportToOpenAPI(endpoints: APIEndpoint[], metadata?: {
    title?: string
    version?: string
    description?: string
    servers?: Array<{ url: string; description?: string }>
  }): string {
    const spec: any = {
      openapi: '3.0.0',
      info: {
        title: metadata?.title || 'Discovered API',
        version: metadata?.version || '1.0.0',
        description: metadata?.description || 'API discovered and documented by ChickAPI'
      },
      servers: metadata?.servers || [{ url: 'https://api.example.com' }],
      paths: {},
      components: {
        schemas: {},
        securitySchemes: {}
      }
    }

    // Group endpoints by path
    const pathGroups = new Map<string, APIEndpoint[]>()
    for (const endpoint of endpoints) {
      const path = this.normalizePathForOpenAPI(endpoint.url)
      if (!pathGroups.has(path)) {
        pathGroups.set(path, [])
      }
      pathGroups.get(path)!.push(endpoint)
    }

    // Build paths
    for (const [path, pathEndpoints] of pathGroups) {
      spec.paths[path] = {}
      
      for (const endpoint of pathEndpoints) {
        const method = endpoint.method.toLowerCase()
        spec.paths[path][method] = this.buildOpenAPIOperation(endpoint)
        
        // Add security schemes
        if (endpoint.authentication) {
          this.addSecurityScheme(spec, endpoint.authentication)
        }
      }
    }

    return JSON.stringify(spec, null, 2)
  }

  // Export to Postman Collection v2.1
  exportToPostman(endpoints: APIEndpoint[], collectionName?: string): string {
    const collection: any = {
      info: {
        name: collectionName || 'Discovered API Collection',
        description: 'API collection generated by ChickAPI',
        schema: 'https://schema.getpostman.com/json/collection/v2.1.0/collection.json'
      },
      item: [],
      variable: [],
      auth: null
    }

    // Group endpoints by tags
    const tagGroups = new Map<string, APIEndpoint[]>()
    for (const endpoint of endpoints) {
      const tag = endpoint.tags?.[0] || 'default'
      if (!tagGroups.has(tag)) {
        tagGroups.set(tag, [])
      }
      tagGroups.get(tag)!.push(endpoint)
    }

    // Build collection items
    for (const [tag, tagEndpoints] of tagGroups) {
      const folder: any = {
        name: tag,
        item: []
      }

      for (const endpoint of tagEndpoints) {
        folder.item.push(this.buildPostmanRequest(endpoint))
      }

      collection.item.push(folder)
    }

    return JSON.stringify(collection, null, 2)
  }

  // Export to HAR (HTTP Archive) format
  exportToHAR(endpoints: APIEndpoint[]): string {
    const har: any = {
      log: {
        version: '1.2',
        creator: {
          name: 'ChickAPI',
          version: '1.0.0'
        },
        entries: []
      }
    }

    for (const endpoint of endpoints) {
      har.log.entries.push(this.buildHAREntry(endpoint))
    }

    return JSON.stringify(har, null, 2)
  }

  // Export to Markdown documentation
  exportToMarkdown(endpoints: APIEndpoint[]): string {
    let markdown = '# API Documentation\n\n'
    markdown += 'Generated by ChickAPI Discovery Module\n\n'
    markdown += '## Table of Contents\n\n'

    // Group by tags
    const tagGroups = new Map<string, APIEndpoint[]>()
    for (const endpoint of endpoints) {
      const tag = endpoint.tags?.[0] || 'General'
      if (!tagGroups.has(tag)) {
        tagGroups.set(tag, [])
      }
      tagGroups.get(tag)!.push(endpoint)
    }

    // Generate TOC
    for (const [tag] of tagGroups) {
      markdown += `- [${tag}](#${tag.toLowerCase().replace(/\s+/g, '-')})\n`
    }
    markdown += '\n---\n\n'

    // Generate documentation for each group
    for (const [tag, tagEndpoints] of tagGroups) {
      markdown += `## ${tag}\n\n`
      
      for (const endpoint of tagEndpoints) {
        markdown += this.generateMarkdownEndpoint(endpoint)
      }
    }

    return markdown
  }

  // Export to CSV for analysis
  exportToCSV(endpoints: APIEndpoint[]): string {
    const headers = [
      'Method', 'URL', 'Summary', 'Authentication', 
      'Parameters', 'Complexity', 'Source', 'Discovered At'
    ]
    
    const rows = [headers.join(',')]
    
    for (const endpoint of endpoints) {
      const row = [
        endpoint.method,
        `"${endpoint.url}"`,
        `"${endpoint.summary || ''}"`,
        endpoint.authentication?.type || 'none',
        endpoint.parameters?.length || 0,
        endpoint.complexity || 0,
        endpoint.source || '',
        endpoint.discoveredAt ? new Date(endpoint.discoveredAt).toISOString() : ''
      ]
      rows.push(row.join(','))
    }

    return rows.join('\n')
  }

  // Export to AsyncAPI for event-driven APIs
  exportToAsyncAPI(endpoints: APIEndpoint[]): string {
    const spec: any = {
      asyncapi: '2.0.0',
      info: {
        title: 'Discovered Event-Driven API',
        version: '1.0.0'
      },
      channels: {}
    }

    // Filter and convert webhook/event endpoints
    const eventEndpoints = endpoints.filter(e => 
      e.tags?.includes('webhook') || 
      e.tags?.includes('event') ||
      e.url.includes('webhook')
    )

    for (const endpoint of eventEndpoints) {
      const channelName = this.extractChannelName(endpoint.url)
      spec.channels[channelName] = {
        description: endpoint.description || endpoint.summary,
        subscribe: {
          operationId: `subscribe_${channelName}`,
          message: {
            payload: endpoint.requestBody?.schema || { type: 'object' }
          }
        }
      }
    }

    return JSON.stringify(spec, null, 2)
  }

  // Helper methods
  private normalizePathForOpenAPI(url: string): string {
    // Remove query parameters
    let path = url.split('?')[0]
    
    // Remove protocol and domain if present
    if (path.startsWith('http')) {
      const urlObj = new URL(path)
      path = urlObj.pathname
    }
    
    // Ensure path starts with /
    if (!path.startsWith('/')) {
      path = '/' + path
    }
    
    return path
  }

  private buildOpenAPIOperation(endpoint: APIEndpoint): any {
    const operation: any = {
      summary: endpoint.summary,
      description: endpoint.description,
      operationId: this.generateOperationId(endpoint),
      tags: endpoint.tags || [],
      parameters: [],
      responses: {}
    }

    // Add parameters
    if (endpoint.parameters) {
      for (const param of endpoint.parameters) {
        operation.parameters.push(this.buildOpenAPIParameter(param))
      }
    }

    // Add request body
    if (endpoint.requestBody) {
      operation.requestBody = {
        required: true,
        content: {
          [endpoint.requestBody.contentType || 'application/json']: {
            schema: endpoint.requestBody.schema || { type: 'object' },
            examples: endpoint.requestBody.examples
          }
        }
      }
    }

    // Add responses
    if (endpoint.responses && endpoint.responses.length > 0) {
      for (const response of endpoint.responses) {
        operation.responses[response.statusCode] = {
          description: response.description || `Response ${response.statusCode}`,
          content: response.contentType ? {
            [response.contentType]: {
              schema: response.schema || { type: 'object' },
              examples: response.examples
            }
          } : undefined
        }
      }
    } else {
      // Default response
      operation.responses['200'] = {
        description: 'Successful response'
      }
    }

    // Add security
    if (endpoint.authentication) {
      operation.security = [{ [this.getSecuritySchemeName(endpoint.authentication)]: [] }]
    }

    return operation
  }

  private buildOpenAPIParameter(param: EndpointParameter): any {
    return {
      name: param.name,
      in: param.in,
      required: param.required || false,
      description: param.description,
      schema: {
        type: param.type || 'string',
        ...param.validation
      },
      example: param.example
    }
  }

  private addSecurityScheme(spec: any, auth: any) {
    const schemeName = this.getSecuritySchemeName(auth)
    
    if (!spec.components.securitySchemes[schemeName]) {
      switch (auth.type) {
        case 'bearer':
          spec.components.securitySchemes[schemeName] = {
            type: 'http',
            scheme: 'bearer',
            bearerFormat: 'JWT'
          }
          break
        case 'apikey':
          spec.components.securitySchemes[schemeName] = {
            type: 'apiKey',
            in: 'header',
            name: auth.parameterName || 'X-API-Key'
          }
          break
        case 'basic':
          spec.components.securitySchemes[schemeName] = {
            type: 'http',
            scheme: 'basic'
          }
          break
        case 'oauth2':
          spec.components.securitySchemes[schemeName] = {
            type: 'oauth2',
            flows: {
              implicit: {
                authorizationUrl: 'https://api.example.com/oauth/authorize',
                scopes: {}
              }
            }
          }
          break
      }
    }
  }

  private getSecuritySchemeName(auth: any): string {
    return `${auth.type}Auth`
  }

  private buildPostmanRequest(endpoint: APIEndpoint): any {
    const request: any = {
      name: endpoint.summary || `${endpoint.method} ${endpoint.url}`,
      request: {
        method: endpoint.method,
        header: [],
        url: {
          raw: endpoint.url,
          protocol: 'https',
          host: ['api', 'example', 'com'],
          path: this.extractPathSegments(endpoint.url)
        }
      }
    }

    // Add headers
    if (endpoint.parameters) {
      for (const param of endpoint.parameters.filter(p => p.in === 'header')) {
        request.request.header.push({
          key: param.name,
          value: param.example || '',
          description: param.description
        })
      }
    }

    // Add query parameters
    const queryParams = endpoint.parameters?.filter(p => p.in === 'query')
    if (queryParams && queryParams.length > 0) {
      request.request.url.query = queryParams.map(p => ({
        key: p.name,
        value: p.example || '',
        description: p.description
      }))
    }

    // Add body
    if (endpoint.requestBody) {
      request.request.body = {
        mode: 'raw',
        raw: JSON.stringify(endpoint.requestBody.examples?.[0] || {}, null, 2),
        options: {
          raw: {
            language: 'json'
          }
        }
      }
    }

    // Add authentication
    if (endpoint.authentication) {
      request.request.auth = this.buildPostmanAuth(endpoint.authentication)
    }

    return request
  }

  private buildPostmanAuth(auth: any): any {
    switch (auth.type) {
      case 'bearer':
        return {
          type: 'bearer',
          bearer: [{ key: 'token', value: '{{bearerToken}}', type: 'string' }]
        }
      case 'apikey':
        return {
          type: 'apikey',
          apikey: [
            { key: 'key', value: auth.parameterName || 'X-API-Key', type: 'string' },
            { key: 'value', value: '{{apiKey}}', type: 'string' }
          ]
        }
      case 'basic':
        return {
          type: 'basic',
          basic: [
            { key: 'username', value: '{{username}}', type: 'string' },
            { key: 'password', value: '{{password}}', type: 'string' }
          ]
        }
      default:
        return null
    }
  }

  private buildHAREntry(endpoint: APIEndpoint): any {
    return {
      startedDateTime: endpoint.discoveredAt || new Date().toISOString(),
      time: 0,
      request: {
        method: endpoint.method,
        url: endpoint.url,
        httpVersion: 'HTTP/1.1',
        headers: this.buildHARHeaders(endpoint),
        queryString: this.buildHARQueryString(endpoint),
        postData: endpoint.requestBody ? {
          mimeType: endpoint.requestBody.contentType || 'application/json',
          text: JSON.stringify(endpoint.requestBody.examples?.[0] || {})
        } : undefined
      },
      response: {
        status: endpoint.responses?.[0]?.statusCode || 200,
        statusText: 'OK',
        httpVersion: 'HTTP/1.1',
        headers: [],
        content: {
          size: -1,
          mimeType: endpoint.responses?.[0]?.contentType || 'application/json',
          text: JSON.stringify(endpoint.responses?.[0]?.examples?.[0] || {})
        }
      },
      cache: {},
      timings: {
        send: -1,
        wait: -1,
        receive: -1
      }
    }
  }

  private buildHARHeaders(endpoint: APIEndpoint): any[] {
    const headers = []
    
    if (endpoint.parameters) {
      for (const param of endpoint.parameters.filter(p => p.in === 'header')) {
        headers.push({
          name: param.name,
          value: param.example || ''
        })
      }
    }
    
    return headers
  }

  private buildHARQueryString(endpoint: APIEndpoint): any[] {
    const queryParams = []
    
    if (endpoint.parameters) {
      for (const param of endpoint.parameters.filter(p => p.in === 'query')) {
        queryParams.push({
          name: param.name,
          value: param.example || ''
        })
      }
    }
    
    return queryParams
  }

  private generateMarkdownEndpoint(endpoint: APIEndpoint): string {
    let md = `### ${endpoint.summary || endpoint.method + ' ' + endpoint.url}\n\n`
    
    if (endpoint.description) {
      md += `${endpoint.description}\n\n`
    }
    
    md += `**Endpoint:** \`${endpoint.method} ${endpoint.url}\`\n\n`
    
    if (endpoint.authentication) {
      md += `**Authentication:** ${endpoint.authentication.type}\n\n`
    }
    
    if (endpoint.parameters && endpoint.parameters.length > 0) {
      md += '**Parameters:**\n\n'
      md += '| Name | Type | In | Required | Description |\n'
      md += '|------|------|-----|----------|-------------|\n'
      
      for (const param of endpoint.parameters) {
        md += `| ${param.name} | ${param.type || 'string'} | ${param.in} | ${param.required ? 'Yes' : 'No'} | ${param.description || '-'} |\n`
      }
      md += '\n'
    }
    
    if (endpoint.requestBody) {
      md += '**Request Body:**\n\n'
      md += '```json\n'
      md += JSON.stringify(endpoint.requestBody.schema || {}, null, 2)
      md += '\n```\n\n'
    }
    
    if (endpoint.responses && endpoint.responses.length > 0) {
      md += '**Responses:**\n\n'
      for (const response of endpoint.responses) {
        md += `- **${response.statusCode}**: ${response.description || 'Response'}\n`
      }
      md += '\n'
    }
    
    md += '---\n\n'
    return md
  }

  private generateOperationId(endpoint: APIEndpoint): string {
    const method = endpoint.method.toLowerCase()
    const path = endpoint.url.replace(/[^a-zA-Z0-9]/g, '_')
    return `${method}_${path}`
  }

  private extractPathSegments(url: string): string[] {
    const path = this.normalizePathForOpenAPI(url)
    return path.split('/').filter(s => s)
  }

  private extractChannelName(url: string): string {
    const path = this.normalizePathForOpenAPI(url)
    return path.replace(/[^a-zA-Z0-9]/g, '_')
  }
}
