import { APIEndpoint, EndpointParameter } from './types'

export class TestGenerator {
  // Generate Jest tests for API endpoints
  generateJestTests(endpoints: APIEndpoint[]): string {
    let testCode = `// Auto-generated API tests by ChickAPI
import axios from 'axios'
import { expect } from '@jest/globals'

// Configure axios defaults
const api = axios.create({
  baseURL: process.env.API_BASE_URL || 'https://api.example.com',
  timeout: 30000
})

// Add auth interceptor if needed
api.interceptors.request.use(config => {
  const token = process.env.API_TOKEN
  if (token) {
    config.headers.Authorization = \`Bearer \${token}\`
  }
  return config
})

`

    // Group endpoints by tags
    const tagGroups = this.groupByTags(endpoints)

    for (const [tag, tagEndpoints] of tagGroups) {
      testCode += this.generateTestSuite(tag, tagEndpoints)
    }

    return testCode
  }

  // Generate Postman test scripts
  generatePostmanTests(endpoint: APIEndpoint): string {
    let tests = `// Tests for ${endpoint.method} ${endpoint.url}\n`
    
    tests += `pm.test("Status code is successful", function () {
    pm.response.to.have.status(200);
});

pm.test("Response time is less than 2000ms", function () {
    pm.expect(pm.response.responseTime).to.be.below(2000);
});

pm.test("Content-Type is present", function () {
    pm.response.to.have.header("Content-Type");
});
`

    // Add schema validation if response schema is available
    if (endpoint.responses?.[0]?.schema) {
      tests += `
const schema = ${JSON.stringify(endpoint.responses[0].schema, null, 2)};

pm.test("Response schema is valid", function () {
    const response = pm.response.json();
    pm.expect(tv4.validate(response, schema)).to.be.true;
});
`
    }

    // Add authentication tests
    if (endpoint.authentication) {
      tests += `
pm.test("Request includes authentication", function () {
    const authHeader = pm.request.headers.get("Authorization");
    pm.expect(authHeader).to.not.be.undefined;
});
`
    }

    return tests
  }

  // Generate Playwright API tests
  generatePlaywrightTests(endpoints: APIEndpoint[]): string {
    let testCode = `// Auto-generated Playwright API tests
import { test, expect } from '@playwright/test'

const BASE_URL = process.env.API_BASE_URL || 'https://api.example.com'
const API_TOKEN = process.env.API_TOKEN

`

    for (const endpoint of endpoints) {
      testCode += this.generatePlaywrightTest(endpoint)
    }

    return testCode
  }

  // Generate Newman (Postman CLI) collection
  generateNewmanCollection(endpoints: APIEndpoint[]): any {
    const collection = {
      info: {
        name: 'Auto-generated API Tests',
        description: 'Test collection generated by ChickAPI',
        schema: 'https://schema.getpostman.com/json/collection/v2.1.0/collection.json'
      },
      item: [],
      event: [
        {
          listen: 'prerequest',
          script: {
            type: 'text/javascript',
            exec: [
              'pm.environment.set("timestamp", new Date().toISOString());',
              'pm.environment.set("randomId", Math.floor(Math.random() * 1000));'
            ]
          }
        }
      ]
    }

    for (const endpoint of endpoints) {
      collection.item.push(this.generateNewmanItem(endpoint))
    }

    return collection
  }

  // Generate security tests
  generateSecurityTests(endpoint: APIEndpoint): string {
    let tests = `// Security tests for ${endpoint.method} ${endpoint.url}\n\n`

    // SQL Injection tests
    if (endpoint.parameters?.some(p => p.in === 'query')) {
      tests += this.generateSQLInjectionTest(endpoint)
    }

    // XSS tests
    if (endpoint.method === 'POST' || endpoint.method === 'PUT') {
      tests += this.generateXSSTest(endpoint)
    }

    // Authentication tests
    if (endpoint.authentication) {
      tests += this.generateAuthenticationTest(endpoint)
    }

    // Rate limiting tests
    if (endpoint.rateLimit) {
      tests += this.generateRateLimitTest(endpoint)
    }

    return tests
  }

  // Generate performance tests using K6
  generateK6Tests(endpoints: APIEndpoint[]): string {
    let testCode = `// K6 Performance tests
import http from 'k6/http'
import { check, sleep } from 'k6'
import { Rate } from 'k6/metrics'

const errorRate = new Rate('errors')

export const options = {
  stages: [
    { duration: '30s', target: 10 },
    { duration: '1m', target: 20 },
    { duration: '30s', target: 0 },
  ],
  thresholds: {
    http_req_duration: ['p(95)<500'],
    errors: ['rate<0.1'],
  },
}

const BASE_URL = __ENV.API_BASE_URL || 'https://api.example.com'
const API_TOKEN = __ENV.API_TOKEN

export default function () {
`

    for (const endpoint of endpoints) {
      testCode += this.generateK6Test(endpoint)
    }

    testCode += `\n  sleep(1)\n}\n`

    return testCode
  }

  // Helper methods
  private groupByTags(endpoints: APIEndpoint[]): Map<string, APIEndpoint[]> {
    const groups = new Map<string, APIEndpoint[]>()
    
    for (const endpoint of endpoints) {
      const tag = endpoint.tags?.[0] || 'General'
      if (!groups.has(tag)) {
        groups.set(tag, [])
      }
      groups.get(tag)!.push(endpoint)
    }
    
    return groups
  }

  private generateTestSuite(tag: string, endpoints: APIEndpoint[]): string {
    let suite = `describe('${tag} API Tests', () => {\n`
    
    for (const endpoint of endpoints) {
      suite += this.generateJestTest(endpoint)
    }
    
    suite += `})\n\n`
    return suite
  }

  private generateJestTest(endpoint: APIEndpoint): string {
    const testName = endpoint.summary || `${endpoint.method} ${endpoint.url}`
    let test = `  test('${testName}', async () => {\n`
    
    // Build request options
    test += `    const response = await api.request({\n`
    test += `      method: '${endpoint.method}',\n`
    test += `      url: '${this.buildTestUrl(endpoint)}',\n`
    
    // Add headers
    if (endpoint.parameters?.some(p => p.in === 'header')) {
      test += `      headers: {\n`
      for (const param of endpoint.parameters.filter(p => p.in === 'header')) {
        test += `        '${param.name}': '${this.generateTestValue(param)}',\n`
      }
      test += `      },\n`
    }
    
    // Add query parameters
    if (endpoint.parameters?.some(p => p.in === 'query')) {
      test += `      params: {\n`
      for (const param of endpoint.parameters.filter(p => p.in === 'query')) {
        test += `        ${param.name}: '${this.generateTestValue(param)}',\n`
      }
      test += `      },\n`
    }
    
    // Add request body
    if (endpoint.requestBody) {
      test += `      data: ${this.generateTestBody(endpoint.requestBody)},\n`
    }
    
    test += `    })\n\n`
    
    // Add assertions
    test += `    expect(response.status).toBeLessThan(400)\n`
    
    if (endpoint.responses?.[0]?.schema) {
      test += `    expect(response.data).toBeDefined()\n`
      
      if (endpoint.responses[0].schema.type === 'array') {
        test += `    expect(Array.isArray(response.data)).toBe(true)\n`
      } else if (endpoint.responses[0].schema.type === 'object') {
        test += `    expect(typeof response.data).toBe('object')\n`
      }
    }
    
    test += `  })\n\n`
    return test
  }

  private generatePlaywrightTest(endpoint: APIEndpoint): string {
    const testName = endpoint.summary || `${endpoint.method} ${endpoint.url}`
    let test = `test('${testName}', async ({ request }) => {\n`
    
    test += `  const response = await request.${endpoint.method.toLowerCase()}(\`\${BASE_URL}${endpoint.url}\`, {\n`
    
    // Add headers
    if (endpoint.authentication || endpoint.parameters?.some(p => p.in === 'header')) {
      test += `    headers: {\n`
      if (endpoint.authentication?.type === 'bearer') {
        test += `      'Authorization': \`Bearer \${API_TOKEN}\`,\n`
      }
      for (const param of endpoint.parameters?.filter(p => p.in === 'header') || []) {
        test += `      '${param.name}': '${this.generateTestValue(param)}',\n`
      }
      test += `    },\n`
    }
    
    // Add request body
    if (endpoint.requestBody) {
      test += `    data: ${this.generateTestBody(endpoint.requestBody)},\n`
    }
    
    test += `  })\n\n`
    
    test += `  expect(response.status()).toBeLessThan(400)\n`
    test += `  const body = await response.json()\n`
    test += `  expect(body).toBeDefined()\n`
    test += `})\n\n`
    
    return test
  }

  private generateNewmanItem(endpoint: APIEndpoint): any {
    return {
      name: endpoint.summary || `${endpoint.method} ${endpoint.url}`,
      request: {
        method: endpoint.method,
        url: endpoint.url,
        header: this.generateNewmanHeaders(endpoint),
        body: endpoint.requestBody ? {
          mode: 'raw',
          raw: JSON.stringify(this.generateTestBody(endpoint.requestBody), null, 2),
          options: { raw: { language: 'json' } }
        } : undefined
      },
      event: [
        {
          listen: 'test',
          script: {
            type: 'text/javascript',
            exec: this.generatePostmanTests(endpoint).split('\n')
          }
        }
      ]
    }
  }

  private generateNewmanHeaders(endpoint: APIEndpoint): any[] {
    const headers = []
    
    if (endpoint.authentication?.type === 'bearer') {
      headers.push({
        key: 'Authorization',
        value: 'Bearer {{API_TOKEN}}'
      })
    }
    
    for (const param of endpoint.parameters?.filter(p => p.in === 'header') || []) {
      headers.push({
        key: param.name,
        value: this.generateTestValue(param)
      })
    }
    
    return headers
  }

  private generateSQLInjectionTest(endpoint: APIEndpoint): string {
    return `test('SQL Injection prevention', async () => {
    const maliciousInputs = [
      "' OR '1'='1",
      "1; DROP TABLE users--",
      "admin'--",
      "' UNION SELECT * FROM users--"
    ]
    
    for (const input of maliciousInputs) {
      const response = await api.request({
        method: '${endpoint.method}',
        url: '${endpoint.url}',
        params: { id: input },
        validateStatus: () => true
      })
      
      expect(response.status).not.toBe(200)
      expect(response.data).not.toContain('SQL')
      expect(response.data).not.toContain('syntax')
    }
  })
  
`
  }

  private generateXSSTest(endpoint: APIEndpoint): string {
    return `test('XSS prevention', async () => {
    const xssPayloads = [
      '<script>alert("XSS")</script>',
      '<img src=x onerror=alert("XSS")>',
      'javascript:alert("XSS")',
      '<svg onload=alert("XSS")>'
    ]
    
    for (const payload of xssPayloads) {
      const response = await api.request({
        method: '${endpoint.method}',
        url: '${endpoint.url}',
        data: { input: payload },
        validateStatus: () => true
      })
      
      if (response.status === 200) {
        expect(response.data).not.toContain(payload)
        expect(response.data).not.toContain('<script>')
      }
    }
  })
  
`
  }

  private generateAuthenticationTest(endpoint: APIEndpoint): string {
    return `test('Authentication required', async () => {
    // Test without auth
    const responseWithoutAuth = await api.request({
      method: '${endpoint.method}',
      url: '${endpoint.url}',
      headers: { Authorization: undefined },
      validateStatus: () => true
    })
    
    expect(responseWithoutAuth.status).toBe(401)
    
    // Test with invalid auth
    const responseWithInvalidAuth = await api.request({
      method: '${endpoint.method}',
      url: '${endpoint.url}',
      headers: { Authorization: 'Bearer invalid_token' },
      validateStatus: () => true
    })
    
    expect(responseWithInvalidAuth.status).toBe(401)
  })
  
`
  }

  private generateRateLimitTest(endpoint: APIEndpoint): string {
    const limit = endpoint.rateLimit?.limit || 100
    return `test('Rate limiting', async () => {
    const requests = []
    
    // Send requests up to the limit
    for (let i = 0; i < ${limit + 10}; i++) {
      requests.push(api.request({
        method: '${endpoint.method}',
        url: '${endpoint.url}',
        validateStatus: () => true
      }))
    }
    
    const responses = await Promise.all(requests)
    const rateLimitedResponses = responses.filter(r => r.status === 429)
    
    expect(rateLimitedResponses.length).toBeGreaterThan(0)
  })
  
`
  }

  private generateK6Test(endpoint: APIEndpoint): string {
    let test = `  // Test ${endpoint.method} ${endpoint.url}\n`
    test += `  const ${this.sanitizeName(endpoint.url)}_response = http.${endpoint.method.toLowerCase()}(\n`
    test += `    \`\${BASE_URL}${endpoint.url}\`,\n`
    
    if (endpoint.requestBody) {
      test += `    JSON.stringify(${this.generateTestBody(endpoint.requestBody)}),\n`
    } else {
      test += `    null,\n`
    }
    
    test += `    {\n`
    test += `      headers: {\n`
    test += `        'Content-Type': 'application/json',\n`
    
    if (endpoint.authentication?.type === 'bearer') {
      test += `        'Authorization': \`Bearer \${API_TOKEN}\`,\n`
    }
    
    test += `      },\n`
    test += `    }\n`
    test += `  )\n\n`
    
    test += `  check(${this.sanitizeName(endpoint.url)}_response, {\n`
    test += `    '${endpoint.url} status is 200': (r) => r.status === 200,\n`
    test += `    '${endpoint.url} response time < 500ms': (r) => r.timings.duration < 500,\n`
    test += `  })\n\n`
    
    test += `  errorRate.add(${this.sanitizeName(endpoint.url)}_response.status >= 400)\n\n`
    
    return test
  }

  private buildTestUrl(endpoint: APIEndpoint): string {
    let url = endpoint.url
    
    // Replace path parameters with test values
    url = url.replace(/{(\w+)}/g, (match, param) => {
      if (param.includes('id') || param.includes('Id')) {
        return '123'
      }
      if (param.includes('uuid')) {
        return '550e8400-e29b-41d4-a716-446655440000'
      }
      return 'test'
    })
    
    return url
  }

  private generateTestValue(param: EndpointParameter): string {
    if (param.example) {
      return String(param.example)
    }
    
    switch (param.type) {
      case 'number':
      case 'integer':
        return '123'
      case 'boolean':
        return 'true'
      case 'email':
        return 'test@example.com'
      case 'date':
        return new Date().toISOString()
      case 'uuid':
        return '550e8400-e29b-41d4-a716-446655440000'
      default:
        return 'test'
    }
  }

  private generateTestBody(requestBody: any): string {
    if (requestBody.examples && requestBody.examples.length > 0) {
      return JSON.stringify(requestBody.examples[0], null, 2)
    }
    
    if (requestBody.schema) {
      return JSON.stringify(this.generateFromSchema(requestBody.schema), null, 2)
    }
    
    return '{}'
  }

  private generateFromSchema(schema: any): any {
    if (!schema) return null
    
    switch (schema.type) {
      case 'object':
        const obj: any = {}
        if (schema.properties) {
          for (const [key, prop] of Object.entries(schema.properties)) {
            obj[key] = this.generateFromSchema(prop as any)
          }
        }
        return obj
        
      case 'array':
        return [this.generateFromSchema(schema.items)]
        
      case 'string':
        if (schema.format === 'email') return 'test@example.com'
        if (schema.format === 'date-time') return new Date().toISOString()
        if (schema.format === 'uuid') return '550e8400-e29b-41d4-a716-446655440000'
        return 'test'
        
      case 'number':
      case 'integer':
        return 123
        
      case 'boolean':
        return true
        
      default:
        return null
    }
  }

  private sanitizeName(url: string): string {
    return url.replace(/[^a-zA-Z0-9]/g, '_').toLowerCase()
  }
}
